# Generated by Django 4.1.6 on 2023-02-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_member_joined_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField(null=True)),
            ],
        ),
    ]
